### ISSUE TITLE
xtec2_theme_onload is not defined

### ISSUE THREAD

**Issue by reskit** [projectestac/moodle-theme_xtec2#2]
Using another theme when xtec2 is installed shows an error in the javascript console:

Uncaught ReferenceError: xtec2_theme_onload is not defined

The above error is causing all menus in Moodle to stop working. To solve the problem temporarily I've comment out calling xtec2_theme_onload function in settings.php file.

**Comment by crazyserver** [comment]
Thanks Marc!

Solved on WIP-MOODLE_28 branch ;-)
